export const metadata = {
  title: "Didongviet.vn",
  description: "Generated by create next app",
};
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import NavFooter from "./components/header/NavFooter";
import Providers from "@/redux/Provider";
import global from "./global.css";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

export default function RootLayout({ children,params }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ToastContainer />
          <Header />
          {children}
          
          <Footer />
          <NavFooter />
        </Providers>
      </body>
    </html>
  );
}
